### ISSUE TITLE
Limitations on # of emails pulled?

### ISSUE THREAD

**Issue by jburdo87** [TiagoGouvea/gmail-to-google-sheets-script#1]
Thanks for this. Any idea why the pull would cut off after 1030 emails (1 month's worth)?
I have it set up to pull emails since March (after:2020/3/31 before:2020/12/17) but it only returns those since Nov.
Any ideas how to correct? Thank you!

**Comment by TiagoGouvea** [comment]
@jburdo87  The script just use the standard gmail service, and it will work exactly the same way, and there's no limit on number os emails pulled.

Trying on my gmail search, searching on date intervals, when I added " and " between the dates, some like "after:2020/12/12 and before:2020/12/17"  it returned less mails than "after:2020/12/12 before:2020/12/17", seams to be the same search, but different results.

I recommend you try to understand better how the search works. 😬

Good luck!

**Comment by TiagoGouvea** [comment]
@jburdo87 I just found that there is a limit, in fact. I updated the script now. Copy and paste it to your code (replacing all ) and run again.

Each page (with 500 emails) could take around 30 seconds to be read.

Tell me if it worked like expected, please.

**Comment by jburdo87** [comment]
Thanks @TiagoGouvea. The revised code worked, without needing to add the "AND" modifier in the search variables. 
Note: For me at least, each page of emails took around 1.45 mins to read. It was worth the wait though, as it ended up generating 12k emails!

**Comment by TiagoGouvea** [comment]
@jburdo87 it really worked then. Sucess! 🎉
